

  
  
  const jokes = ["    Q: What did one wall say to the other wall? I’ll meet you at the corner!",
  "    What do you call a bear with no teeth? A gummy bear!",
  "    Q: What do you call cheese that isn’t yours? Nacho cheese!",
  "    Q: Where do cows go for entertainment? To the moo-vies!",
  "    Knock, knock. Who’s there? Cows go. Cows go who? No, cows go MOO!",
  "    Q:  What do you call a cow with no legs? Ground beef!",
  "    Q: What do you call a cow with two legs? Lean meat!",
  "    Q:  What do you call a pig that knows karate? A pork chop!",
  "     Q: Why are ghosts bad liars? Because you can see right through them!",
  "     Q: What animal needs to wear a wig? A bald eagle!",
  "     Q: What do you call a fly without wings? A walk!",
  "     Knock knock. Who’s there? A little old lady? A little old lady who? I didn’t know you could yodel!",
  "     Q: Why do bees have sticky hair? Because they use honey combs!",
  "     Q: What do you call an alligator in a vest? An investigator!",
  "     Q:  Why can’t you give Elsa a balloon? Because she will let it go!",
  "     Q: What do you get when you cross a snowman with a vampire Frostbite!",
  "     Q:  What has four wheels and flies? A garbage truck!",
  "     Q:  Why did the man run around his bed? Because he was trying to catch up on his sleep!",
  "     Q:  Why did the math book look so sad? Because it had so many problems!",
  "     Q:  Can a kangaroo jump higher than the Empire State Building? Of course!  The Empire State Building can’t jump!",
  "     Q:  If April showers bring Mayflowers, what do Mayflowers bring?Pilgrims!",
  "     Q: What do you call a sleeping bull? A bulldozer!",
  "     Q: What did the zero say to the eight? Nice belt!",
  "     Q:  Why do sharks swim in saltwater? Because pepper water makes them sneeze!",
  "     Q: Where do you find a dog with no legs? Right where you left him!",
  "     Q:  Where do fish keep their money? In the river bank!",
  "     Q:  Why did the gum cross the road? It was stuck to the chicken’s foot!",
  "     Q:  What is brown and sticky? A stick!",
  "     Q:  Why did the picture go to jail? It was framed!",
  "     Q: How do you know if there’s an elephant under your bed? Your head hits the ceiling!",
  "     Q: Why are elephants so wrinkled? Because they take too long to iron!",
  "     Q: How do you keep an elephant from charging? Take away her credit card!",
  "     Q:  Why did the elephant paint himself different colors? So he could hide in the crayon box!",
  "     Q:  How can you tell if an elephant has been in your refrigerator?By the footprints in the butter!",
  "     Q: What is the difference between elephants and grapes? Grapes are purple.",
  "     Q:  What did Tarzan say when he saw the elephants coming? “Here come the elephants!”",
  "     Q:  What did Jane say when she saw the elephants coming? “Here come the grapes!” (She was colorblind.)",
  "     Q:  Why did the chicken cross the playground? To get to the other slide!",
  "     Q:  What can you catch but not throw? A cold!",
  "     Q:  What has hands but can’t clap? A clock!",
  "     Q: What do you call a dog that can tell time? A watch dog!",
  "     Q:  What did one hat say to the other? Stay here, I’m going on ahead. (going on a head)",
  "     Q:  What side of a turkey has the most feathers? The outside!",
  "     Q:  What falls in winter but never gets hurt? The snow!",
  "     Q:  Why did the teacher put on sunglasses? Because her students were so bright! ",
  "     Q: How did Benjamin Franklin feel when he discovered electricity? Shocked!",
  "     Q:  Why do strings never win a race? Because they always tie!",
  "     Q:  What kind of shoes do ninjas wear? Sneakers!",
  "     Q: What do you call a flower that runs on electricity? A power plant!",
  "     Q: Why couldn’t the pony sing in the choir? Because she was a little horse!",
  "     Q: Why did the cookie go to the nurse? Because he felt crummy!",
  "     Q: What kind of room doesn’t have doors? A mushroom!",
  "     Q: What has four wheels and flies? A garbage truck!",
  "     Q: How do you keep a bull from charging? Take away its credit card!",
  "     Q: What did one plate say to the other? Dinner is on me!",
  "     Q: How do you make a lemon drop? Just let go of it! ",
  "     Q: Why did the boy throw his clock out the window? Because he wanted to see time fly!",
  "     Q: What does an evil hen lay? Deviled eggs!",
  "     Q: Which hand is better to write with? Neither. It’s better to write with a pencil!",
  "     Q: What did the traffic light say to the truck? Don’t look! I’m changing!",
  "     Q: What is the witch’s favorite school subject? Spelling!",
  "     Q: What did the frog order for lunch? A burger and a diet croak!",
  "     Q: Why did the teddy bear not want any dessert? Because she was stuffed!",
  "     Q: What do you call a fly without wings? A walk.",
  "     Q: Why should you never trust a pig with a secret? Because it’s bound to squeal.",
  "     Q: What do cows order from? Cattle-logs!",
  "     Q: What’s the difference between broccoli and boogers? Kids don’t eat broccoli!",
  "     Q: What kind of haircuts do bees get? Buzzzzcuts!",
  "     Q: How can you tell if someone is a good farmer? He is outstanding in his field! ",
  "     Q: What do you call a man with a shovel? Doug. ",
  "     Q: How do mountains stay warm in winter? Snowcaps",
  "     Q: Why can’t a person’s nose be 12 inches long? Because then it would be a foot!",
  "     Q: What has a ton of ears but can’t hear a thing? A corn field.",
  "     Q: What do you call the horse that lives next door? Your neighbor!",
  "     Q: What kind of shoes do spies wear? Sneakers!",
  "     Q: Why did the man put sugar on his pillow? He wanted to have sweet dreams!",
  "     Q: Why did the computer sneeze? Because it had a virus!",
  "     Q: What do you call two banana peels? A pair of slippers!",
  "     Q: What do you call a cow who gets her way all the time? Spoiled milk!",
  "     Q: How does a scientist freshen her breath? With experiments! (experi-mints!)",
  "     Q: What is a computer programmer’s favorite snack? Computer chips!",
  "     Q: Why do hummingbirds hum? Because they don’t know the words!",
  "     Q: What do you call a mad elephant? An earthquake!",
  "     Q: Why do birds fly south in the winter? Because it’s too far to walk!",
  "     Q: What do you get on every birthday? A year older!",
  "     Q: Why should you not talk to circles? Because there is no point!",
  "     Q: Why is it dangerous to play cards in the jungle? Because there are so many CHEETAHS! (cheaters)",
  "     Q: How do you fix a cracked pumpkin? With a pumpkin patch!",
  "     Q: Why do seagulls fly over the sea? Because if they flew over the bay, they would be bagels.",
  "     Q: How many apples grow on a tree? All of them!",
  "     Q: What’s gray and goes round and round? An elephant in a washing machine!",
  "     Q: Why can’t an egg tell a joke? It will crack up!",
  "     Q: Why did the golfer wear two pairs of pants? In case he got a hole in one!",
  "     Q: What do fish play on the piano? Scales!",
  "     Q: Where do hamburgers go dancing? A meat ball!",
  "     Q: How do billboards talk? Sign language!",
  "     Q: What do snakes like to study in school? Hissss-tory!",
  "     Q: What kind of music do balloons hate? Pop music.",
  "    . Q: What do you call a sad strawberry? A blueberry!",
  "    . Q: What do you call a cow that can’t moo? A milk dud."];

  const joke=document.getElementById('jokesme');
  const btn=document.getElementById('jokeButton');
  
  btn.addEventListener('click',randomjoke);

  function randomjoke(){
  var no=Math.floor(Math.random()*100);
  joke.innerHTML=jokes[no];

  }